language: node_js
node_js:
  - node
services:
  - postgresql

before_install:
  - psql -c 'create database WayFareTestDb;' -U postgres

install:
  - npm install

script:
  - npm run test
after_success:
  - npm run coveralls 
